# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Видимость')),
                ('likes', models.SmallIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('views', models.SmallIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Видимость')),
                ('likes', models.SmallIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('views', models.SmallIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('date_of_start', models.DateField(verbose_name='Дата начала')),
                ('date_of_finish', models.DateField(blank=True, verbose_name='Дата завершения')),
                ('time_of_start', models.TimeField(verbose_name='Время начала')),
                ('time_of_finish', models.TimeField(blank=True, verbose_name='Время завершения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='mainApp.Categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('adress', models.TextField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя для регистации через имейл')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес для регистации через имейл')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка для регистрации')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждение регистрации')),
                ('site_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Place'),
        ),
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Event'),
        ),
    ]
