# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20160713_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Event'),
        ),
    ]
