# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20160713_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='mainApp.Categories'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_finish',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_finish',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время завершения'),
        ),
    ]
