# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20160713_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='CategoriesEvents',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='mainApp.CategoriesPlaces'),
        ),
    ]
