# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20160716_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=models.TextField(default='blablabla', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
