# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_place_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='mainApp.CategoriesEvents'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='mainApp.CategoriesPlaces'),
        ),
    ]
