# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20160721_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Возможность комментариев'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Возможность комментариев'),
        ),
        migrations.AddField(
            model_name='event',
            name='need_registration',
            field=models.BooleanField(default=True, verbose_name='Возможность зарегистрироваться на событие'),
        ),
    ]
