# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20160726_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя для регистации через имейл'),
        ),
    ]
