# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20160818_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='site_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
