# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024, verbose_name='Текст комментария')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Текст комментария')),
                ('subject_type', models.CharField(choices=[('Event', 'Event'), ('Article', 'Article')], max_length=20)),
                ('subject_id', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentsarticles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentsarticles',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='commentsevents',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentsevents',
            name='subject',
        ),
        migrations.DeleteModel(
            name='CommentsArticles',
        ),
        migrations.DeleteModel(
            name='CommentsEvents',
        ),
    ]
