# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countViews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('viewed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='countViews.Viewed')),
            ],
            bases=('countViews.viewed',),
        ),
    ]
